version: "3.8"
services:
  email_sender_api:
    image: elleined/email-sender-api:latest
    container_name: email_sender_api
    env_file:
      - .env
    ports:
      - "8091:8091"
    networks:
      - esa_network

networks:
  esa_network:
    name: esa_network
    external: false
    ipam:
      driver: default